from mcp.server.fastmcp import FastMCP
from pydantic import ValidationError

from app.core.docx_gen import create_lba
from app.templates.registry import TEMPLATES, get_template_entry
from app.core.merge_engine import render as merge_render
from app.core.email_sender import send_email

mcp = FastMCP("matter-document-generator", "1.0.0")

@mcp.resource("templates://list")
def list_templates() -> dict:
    """List every registered email template ID and its required parameters."""
    return{
        template_id: list(template_entry.schema.model_fields.keys())
        for template_id, template_entry in TEMPLATES.items()
    }

@mcp.tool()
def render_email(template_id: str, payload: dict) -> dict:
    """
    Render (but do not send) an email from a registered template.
    template_id must match one of the IDs from templates://list.
    payload must satisfy that template's exact field schema — no extra
    or missing fields are permitted.
    """
    entry = get_template_entry(template_id)
    if entry is None:
        return {"error": f"Unknown template_id '{template_id}'"}

    try:
        data = entry.schema.model_validate(payload)
    except ValidationError as exc:
        return {"error": exc.errors()}

    result = merge_render(entry, data)
    return {"subject": result.subject, "body": result.body}

@mcp.tool()
def generate_lba_docx(lba_name: str, recipient_name: str, legal_basis: str, demands: str,) -> dict:
    """
    Generate a Letter Before Action DOCX and return its local file path.
    Use the returned path as attachment_paths=[...] in send_email_tool.
    """

    docx_path = create_lba(
        lba_name=lba_name,
        recipient_name=recipient_name,
        legal_basis=legal_basis,
        demands=demands,
    )

    return {
        'status': 'success',
        'docx_name': docx_path.name,
        'docx_path': str(docx_path),
    }

@mcp.tool()
def generate_lba_pdf(lba_name: str, recipient_name: str, legal_basis: str, demands: str,) -> dict:
    """
    Generate a Letter Before Action PDF and return its local file path.
    Use the returned path as attachment_paths=[...] in send_email_tool.
    """

    pdf_path = create_lba(
        lba_name=lba_name,
        recipient_name=recipient_name,
        legal_basis=legal_basis,
        demands=demands,
    )

    return {
        'status': 'success',
        'pdf_name': pdf_path.name,
        'pdf_path': str(pdf_path),
    }

@mcp.tool()
def send_email_tool(
    template_id: str,
    to: str,
    payload: dict,
    confirm: bool,
    attachment_paths: list[str] | None = None,
) -> dict:
    """
    Send an email from a registered template. Sends real client
    correspondence — confirm must be explicitly set to true, and this
    should only be called after the caller has shown the rendered
    preview (via render_email) to a human for approval.

    Optional attachment_paths should contain local file paths, such as
    DOCX files generated by app.core.doc_gens.docx_gen.create_lba; or as PDF files generated by app.core.doc_gens.pdf_gen.create_lba
    """
    if not confirm:
        return {"error": "confirm must be true to send an email"}

    entry = get_template_entry(template_id)
    if entry is None:
        return {"error": f"Unknown template_id '{template_id}'"}

    try:
        data = entry.schema.model_validate(payload)
    except ValidationError as exc:
        return {"error": exc.errors()}

    result = merge_render(entry, data)
    try:
        send_email(
            to=to,
            subject=result.subject,
            body=result.body,
            attachments=attachment_paths,
        )
    except FileNotFoundError as exc:
        return {"error": str(exc)}

    return {
        "status": "sent",
        "subject": result.subject,
        "attachment_count": len(attachment_paths or []),
    }


if __name__ == "__main__":
    mcp.run()
